stages:
  - test
  - build


unit:
  stage: test
  image: registry.gitlab.com/mbarkhau/pylint-ignore/base
  script:
    - make lint
    - make mypy
    - make test
  coverage: '/^(TOTAL|src).*?(\d+\%)$/'
  artifacts:
    reports:
      junit:
        - reports/flake8.xml
        - reports/pytest.xml
    paths:
      - reports/htmlcov/
      - reports/mypycov/
  allow_failure: false


pages:
  stage: build
  script:
    - mkdir -p public/cov
    - mkdir -p public/mypycov
    - cp -r reports/htmlcov/* public/cov/
    - cp -r reports/mypycov/* public/mypycov/
  artifacts:
    paths:
      - public
  only:
    - master
